-- Performance indexes identified by the Phase 3 backend performance audit
-- (2026-09-18). All four are plain, non-destructive CREATE INDEX statements —
-- no columns, tables, or data are altered. Matches the @@index declarations
-- added to prisma/schema.prisma in the same change.
--
-- NOT YET APPLIED to any database — this file was generated by hand because
-- `prisma migrate dev` could not reach the local dev database to run its
-- normal generate+apply flow. Review, then apply via the project's existing
-- `bun run prisma:migrate` (dev) or `bun run prisma:deploy` (prod) commands.

-- Leaderboard sort: user.controller.ts getLeaderboard orders by
-- xpPoints DESC, level DESC, createdAt ASC — User had zero non-unique
-- indexes, so this was a full-table sort on every call.
CREATE INDEX IF NOT EXISTS "users_xp_leaderboard_idx" ON "users"("xp_points" DESC, "level" DESC, "created_at" ASC);

-- getMyRides (ride.controller.ts) filters creatorId [+ status], orders by
-- endedAt desc. Ride.creatorId had no index at all — Prisma/Postgres does
-- not auto-index foreign-key scalar columns.
CREATE INDEX IF NOT EXISTS "rides_creator_status_ended_idx" ON "rides"("creator_id", "status", "ended_at" DESC);

-- Monthly leaderboard (user.controller.ts) filters status = 'COMPLETED' AND
-- endedAt >= start-of-month. Distinct from the existing (status, scheduledAt)
-- index, which doesn't cover endedAt.
CREATE INDEX IF NOT EXISTS "rides_status_ended_idx" ON "rides"("status", "ended_at");

-- RideParticipant's only index is @@unique([rideId, userId]), which leads
-- with rideId and so doesn't serve userId-only lookups. Hit once per rider
-- on every ride-end (xp.ts evaluateAndAwardRideBadges -> rideParticipant.count).
CREATE INDEX IF NOT EXISTS "ride_participants_user_status_idx" ON "ride_participants"("user_id", "status");
